- name: install general packages
  yum: name={{item}} state=present
  with_items:
    - rsync
    - git
    - emacs-nox
    - python-dateutil
  become: yes

- name: install s3cfg
  synchronize: src=../../.s3cfg dest=/home/mdomsch/.s3cfg

- name: sync s3cmd git tree
  synchronize:
     src: ../s3cmd
     dest: /home/mdomsch/s3cmd/
     rsync_opts:
       - "--exclude=testsuite/"
